export type Brand =
  | "Flock Safety"
  | "Motorola"
  | "Genetec"
  | "Leonardo"
  | "Neology"
  | "Other";

export interface Camera {
  /** OSM node id (stable across syncs). */
  id: string;
  lat: number;
  lon: number;
  brand: Brand;
  /** Raw manufacturer/brand string from OSM, kept for display/debugging. */
  rawBrand?: string;
  /** Facing direction(s) in degrees if tagged, e.g. [90, 270]. */
  directions: number[];
  /** Whether the camera covers all directions (surveillance:zone/360). */
  omni: boolean;
}

export interface CameraDataset {
  /** ISO timestamp of when the pack was generated by the fetch script. */
  generatedAt: string;
  /** ISO timestamp of when this device last pulled the pack. */
  syncedAt?: string;
  count: number;
  cameras: Camera[];
}

export interface LatLng {
  lat: number;
  lon: number;
}

export interface SavedRoute {
  id: string;
  createdAt: string;
  origin: LatLng;
  destination: LatLng;
  destinationLabel: string;
  /** [lon, lat] pairs (GeoJSON order) for the chosen (avoidance) route. */
  coordinates: [number, number][];
  distanceMeters: number;
  durationSeconds: number;
  /** Cameras within the corridor of the fastest route. */
  camerasOnFastest: number;
  /** Cameras still within the corridor of this avoidance route. */
  camerasUnavoidable: number;
}

export type AppMode = "drive" | "route" | "settings";

export interface Settings {
  /** Alert trigger distance in feet. */
  alertDistanceFeet: number;
  muted: boolean;
  /** When true, only Flock Safety cameras alert/draw prominently. */
  flockOnly: boolean;
  /** Rotate map to heading (true) or keep north-up (false). */
  headingUp: boolean;
  /** Escalate beep pitch/rate as you get closer. */
  escalate: boolean;
}
